spring:
  cloud:
    gateway:
      routes:
        - id: wiremock
          uri: ${wiremock.host}
          predicates:
            - Path=/**
server:
  port: 8081
wiremock:
  host: http://localhost:8080
management:
  endpoints:
    web:
     exposure:
      include:
        - health
        - prometheus
logging:
  level:
    root: DEBUG
